language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - 2.0.0

before_script:
  - psql -c 'create database hstore_test;' -U postgres
  - psql -c 'create extension if not exists hstore;' -U postgres -d hstore_test
